/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package Theatre;

// Class: TheaterRunner
// Purpose: This program tests the Theater class by making an ArrayList of 
// Customers, making a Theater object, calling the methods & 
// printing the results.
//
// Tim Gallagher
// 2019 APCS A Facebook Summit

import java.util.*;

public class App {

	public static void main(String[] args) {
		
		ArrayList<Customer> customerList1 = getList1();
		Theater theater1 = new Theater(5, 4, customerList1);

		System.out.println("**********************************");
		System.out.println("isOccupied test");
		System.out.println(
				"Seat 2, 3 is occupied and should return true. \nYou said " + theater1.isSeatOccupied(2, 3) + "\n");
		System.out.println(
				"Seat 4, 3 is unoccupied and should return false. \nYou said " + theater1.isSeatOccupied(4, 3) + "\n");

		System.out.println("**********************************");
		System.out.println("Tallest customer test");
		System.out.println("The tallest customer should be: Robert,78 \nYou said " + theater1.getTallestCustomer());

		System.out.println("**********************************");
		

		ArrayList<Customer> customerList2 = getList2();
		Theater theater2 = new Theater(7, 6, customerList2);


		System.out.println("Most occupied row test. \n The most occupied row is row 6 \nYou said the most occupied row was " + theater2.findMostOccupiedRow());
		

		System.out.println("**********************************");
		System.out.println("The customers to be moved should be: \nLaQuane,77\nDrew,78\nWill,74\nEdward,70");
		System.out.println("You should the customers to be moved should be:");
		for(Customer c : theater2.getCustomersToBeMoved()){
			System.out.println(c);
		}
		
		

	}

	public static ArrayList<Customer> getList1(){
		ArrayList<Customer> customerList1 = new ArrayList<Customer>();

		customerList1.add(new Customer("Brandon", 74));
		customerList1.add(new Customer("Matt", 65));
		customerList1.add(new Customer("Noelle", 62));
		customerList1.add(new Customer("Kaleigh", 70));
		customerList1.add(new Customer("Steven", 76));
		customerList1.add(new Customer("Angel", 60));
		customerList1.add(new Customer("Lauren", 68));
		customerList1.add(new Customer("Michael", 64));
		customerList1.add(new Customer("Robin", 63));
		customerList1.add(new Customer("Bryan", 60));
		customerList1.add(new Customer("Kyle", 72));
		customerList1.add(new Customer("Danny", 62));
		customerList1.add(new Customer("Rachel", 64));
		customerList1.add(new Customer("David", 68));
		customerList1.add(new Customer("Sydney", 59));
		customerList1.add(new Customer("Katie", 70));
		customerList1.add(new Customer("Kylie", 54));
		customerList1.add(new Customer("Robert", 78));
		return customerList1;
	}

	public static ArrayList<Customer> getList2(){
		ArrayList<Customer> customerList2 = new ArrayList<Customer>();

		customerList2.add(new Customer("Antoine", 72));
		customerList2.add(new Customer("Jacob", 68));
		customerList2.add(null);

		customerList2.add(new Customer("Jack", 77));
		customerList2.add(null);
		customerList2.add(null);
		customerList2.add(new Customer("Peter", 70));
		customerList2.add(new Customer("Hannah", 70));
		customerList2.add(null);

		customerList2.add(null);

		customerList2.add(new Customer("Jenny", 64));
		customerList2.add(new Customer("Michele", 66));
		customerList2.add(null);
		customerList2.add(new Customer("Ricky", 70));
		customerList2.add(null);

		customerList2.add(new Customer("Niko", 70));
		customerList2.add(null);
		customerList2.add(null);
		customerList2.add(null);

		customerList2.add(new Customer("Chris", 67));
		customerList2.add(new Customer("Holly", 68));
		customerList2.add(null);

		customerList2.add(new Customer("LaQuane", 77));
		customerList2.add(null);
		customerList2.add(null);

		customerList2.add(new Customer("Drew", 78));
		customerList2.add(new Customer("Matt", 71));

		customerList2.add(null);
		customerList2.add(new Customer("Samuel", 65));
		customerList2.add(null);
		customerList2.add(null);
		customerList2.add(new Customer("Deja", 66));
		customerList2.add(new Customer("Will", 74));
		customerList2.add(null);
		customerList2.add(null);

		customerList2.add(new Customer("Edward", 70));
		customerList2.add(new Customer("Nick", 72));

		customerList2.add(null);
		customerList2.add(new Customer("Jamus", 66));
		customerList2.add(new Customer("Carey", 62));
		customerList2.add(new Customer("Sophia", 45));
		customerList2.add(new Customer("Bruce", 53));

		return customerList2;
	}

}
